# frozen_string_literal: true

# Server-side phone-number hashing for contact discovery.
#
# Privacy model: clients send E.164 phone numbers over TLS; the *server*
# hashes them with a secret pepper that never leaves the server. Stored
# hashes are therefore HMACs keyed with a value no client can extract
# (unlike the old scheme where the pepper was embedded in the app binary
# and any extracted copy let an attacker brute-force every stored hash).
#
# Key resolution order:
#   1. ENV["PHONE_HASH_PEPPER"]              (container/Dokku)
#   2. /run/secrets/phone_hash_pepper         (Docker secrets)
#   3. secrets/phone_hash_pepper.txt          (local dev, generated by dev-start.sh)
#   4. Fallback: HMAC derived from Rails.application.secret_key_base so the
#      app boots and tests run even when the pepper file is absent. In
#      production a dedicated pepper MUST be configured — see README.
class PhoneContactHashService
  PEPPER_ENV = "PHONE_HASH_PEPPER"
  PEPPER_SECRET_PATH = "/run/secrets/phone_hash_pepper"
  PEPPER_LOCAL_PATH = Rails.root.join("secrets", "phone_hash_pepper.txt")

  HMAC_DIGEST = OpenSSL::Digest::SHA256.new

  class << self
    # HMAC-SHA256 of the phone number keyed with the server-held pepper.
    def hash_number(number)
      raise ArgumentError, "phone number must be E.164" unless valid_number?(number)

      OpenSSL::HMAC.hexdigest(HMAC_DIGEST, pepper, number)
    end

    def hash_all(numbers)
      numbers.map { |n| hash_number(n) }
    end

    # E.164: a single leading "+" followed by 7-15 digits.
    # We deliberately do not run full libphonenumber here: the client is
    # responsible for normalization, the server only guards the wire format.
    def valid_number?(number)
      number.is_a?(String) && number.match?(/\A\+[1-9]\d{6,14}\z/)
    end

    # A stable identifier for the current pepper (used for cache-busting /
    # debugging; never returns the pepper itself).
    def pepper_fingerprint
      OpenSSL::Digest::SHA256.hexdigest(pepper).slice(0, 12)
    end

    def pepper
      @pepper ||= resolve_pepper
    end

    # Force-reload the pepper (used in tests and when env changes at runtime).
    def reset_pepper!
      @pepper = nil
    end

    private

    def resolve_pepper
      if ENV[PEPPER_ENV].present?
        return ENV[PEPPER_ENV]
      end

      if File.exist?(PEPPER_SECRET_PATH)
        return File.read(PEPPER_SECRET_PATH).strip
      end

      if File.exist?(PEPPER_LOCAL_PATH)
        return File.read(PEPPER_LOCAL_PATH).strip
      end

      fallback_pepper
    end

    def fallback_pepper
      base = Rails.application.secret_key_base
      if base.present?
        OpenSSL::HMAC.hexdigest(HMAC_DIGEST, base, "phone-contact-hash-v1")
      else
        Rails.logger.warn "PhoneContactHashService: no pepper configured, using ephemeral key"
        SecureRandom.hex(32)
      end
    end
  end
end
