# frozen_string_literal: true
class AuthorizationApproval < ApplicationRecord
  # PROTO.md Section 5.7: Approval History tracking
  # Generated by Rails generator - proper table: authorization_approvals

  self.table_name = "authorization_approvals"

  belongs_to :user, foreign_key: :user_id, primary_key: :matrix_user_id, optional: true
  # `miniapp_id` holds a mini app's `app_id` (the "ma_..." identifier), and
  # the class is `MiniApp` — without both spellings out, Rails looks for a
  # `Miniapp` class and a `miniapp_id` column that do not exist.
  belongs_to :miniapp, class_name: "MiniApp", foreign_key: :miniapp_id, primary_key: :app_id, optional: true

  validates :user_id, presence: true
  validates :miniapp_id, presence: true
  validates :scope, presence: true
  validates :approved_at, presence: true

  scope :for_user, ->(user_id) { where(user_id: user_id) }
  scope :for_miniapp, ->(miniapp_id) { where(miniapp_id: miniapp_id) }
  scope :approved, -> { where("approved_at IS NOT NULL") }
  scope :for_scopes, ->(scopes) { where(scope: scopes) }
end
