class AuthorizationApproval < ApplicationRecord
  # PROTO.md Section 5.7: Approval History tracking
  # Generated by Rails generator - proper table: authorization_approvals

  self.table_name = "authorization_approvals"

  belongs_to :user, foreign_key: :user_id, primary_key: :matrix_user_id, optional: true
  belongs_to :miniapp, foreign_key: :miniapp_id, primary_key: :miniapp_id, optional: true

  validates :user_id, presence: true
  validates :miniapp_id, presence: true
  validates :scope, presence: true
  validates :approved_at, presence: true

  scope :for_user, ->(user_id) { where(user_id: user_id) }
  scope :for_miniapp, ->(miniapp_id) { where(miniapp_id: miniapp_id) }
  scope :approved, -> { where("approved_at IS NOT NULL") }
  scope :for_scopes, ->(scopes) { where(scope: scopes) }
end
