class MiniAppAutomatedCheck < ApplicationRecord
  # PROTO.md Section 9.3.1: Automated review checks
  # Generated by Rails generator - proper table: mini_app_automated_checks

  self.table_name = "mini_app_automated_checks"

  belongs_to :miniapp, foreign_key: :miniapp_id, primary_key: :miniapp_id, optional: true

  validates :miniapp_id, presence: true
  validates :status, presence: true

  scope :for_miniapp, ->(miniapp_id) { where(miniapp_id: miniapp_id) }
  scope :latest, -> { order(created_at: :desc).first }
  scope :passed, -> { where(status: "passed") }
  scope :failed, -> { where(status: "failed") }
end
