class MiniAppAppeal < ApplicationRecord
  # PROTO.md Section 9.3.4: Appeal process for rejected mini-apps
  # Generated by Rails generator - proper table: mini_app_appeals

  self.table_name = "mini_app_appeals"

  belongs_to :miniapp, foreign_key: :miniapp_id, primary_key: :miniapp_id, optional: true

  validates :miniapp_id, presence: true
  validates :user_id, presence: true
  validates :reason, presence: true
  validates :status, presence: true

  scope :for_miniapp, ->(miniapp_id) { where(miniapp_id: miniapp_id) }
  scope :pending, -> { where(status: "pending_review") }
  scope :latest, -> { order(created_at: :desc).first }
  scope :for_user, ->(user_id) { where(user_id: user_id) }
end
